### ISSUE TITLE
Different output format(s)?

### ISSUE THREAD

**Issue by KlfJoat** [havrest/go-dvdid#1]
Thanks for this!  I can't get the original `dvdid` to compile for me.  And `pydvdid` is now abandoned bc of the Python2.7 fiasco.  Yours is the only live, usable version I can find!

So, I have a request... I have a number of scripts that directly use the output of `pydvdid`, which is simply the 16-character lowercase hexadecimal dvdid.  Like `1234567890abcdef`.  

Your version outputs 2 lines:
```
2020/04/28 13:06:16 Analysing volume: /mountpoint
2020/04/28 13:06:16 DiscId: 12345678-90ABCDEF
```
Are you willing or able to maybe add an option like `--pydvdid` or `--blob` so that it will output the dvdid in the same format as `pydvdid`?

Thanks!

**Comment by havrest** [comment]
Hi @KlfJoat !

Thank you for your feedback! I updated the dvdid package to output the disc id in a more generic format (binary CRC64) so that the users can display it in the format they want.
I also updated the example dvdid.go to show how to display them in pydvdid format.
